function Datas = ProjectOntoAMA3(Datas, parameters, methods)

%% Construct a Basis of AMA_Perp using the multilevel tree method and project the Class A and B machine data onto this basis


    if ~methods.Multi2.isTallMatrix(Datas.A.CovTraining) 
        [U,~,~] = svd(Datas.A.CovTraining);
       % U(:,1:parameters.snapshots.k1) = [];
       % U = fliplr(U);

        for C = 'AB', for set = ["CovTraining", "Machine", "Testing"]
            Datas.(C).(set) = U'*Datas.(C).(set);
        end, end

    else
        
       
        [~,...
            Datas.A.CovTraining,...
            Datas.A.Machine,...
            Datas.A.Testing,...
            Datas.B.CovTraining,...
            Datas.B.CovTraining,...
            Datas.B.Testing] = ...
            methods.Multi2.BinarySVD(Datas.A.CovTraining,...
            Datas.A.CovTraining,...
            Datas.A.Machine,...
            Datas.A.Testing,...
            Datas.B.CovTraining,...
            Datas.B.CovTraining,...
            Datas.B.Testing);
        
    end


end

