function Datas = ProjectOntoT3(Datas, parameters, methods)

%% Construct a Basis of Clas B using the multilevel tree method and project the Class A and B machine data onto this basis

    XB = Datas.B.CovTraining - mean(Datas.B.CovTraining, 2);
    %XB = Datas.B.CovTraining;
    if ~methods.Multi2.isTallMatrix(Datas.B.CovTraining) 
        [U,~,~] = svd(XB);
      
        for C = 'AB', for set = ["CovTraining", "Machine", "Testing"]
            Datas.(C).(set) = U'*Datas.(C).(set);
        end, end

    

    else
        
        

        [~,...
            Datas.A.CovTraining,...
            Datas.A.Machine,...
            Datas.A.Testing,...
            Datas.B.CovTraining,...
            Datas.B.CovTraining,...
            Datas.B.Testing] = ...
            ...
            methods.Multi2.BinarySVD(XB,...
            Datas.A.CovTraining,...
            Datas.A.Machine,...
            Datas.A.Testing,...
            Datas.B.CovTraining,...
            Datas.B.CovTraining,...
            Datas.B.Testing);


    end

end

