function [Datas, parameters] = CompMultiConstructFilter4(Datas, parameters, methods)

[U,~,~] = svds(Datas.A.CovTraining, parameters.snapshots.k1,'largest');


[~,...
Datas.A.Machine,...
Datas.B.Machine,...
Datas.A.Testing,...
Datas.B.Testing] ...
= ...
methods.Multi2.BinarySVD(U, ...
Datas.A.Machine,...
Datas.B.Machine,...
Datas.A.Testing,...
Datas.B.Testing);

for C = 'AB', for set = ["Machine", "Testing"]
    Datas.(C).(set)(1:parameters.snapshots.k1,:) = [];
end, end

end



